"""record_candidate — persist a lead into the vault's Process/ folder.

Deliberately named "candidate", not "finding": per the critical-vuln-research
methodology a lead is NOT a finding until all four verification gates pass.
The note is written with an explicit gate checklist so nothing gets promoted to
Outputs/ (a reportable finding) until it is actually proven and reproduced.

Notes are timestamp+slug named and never overwrite, so the agent can log many
hypotheses — including dead ends — without clobbering earlier work.
"""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

import config
from .base import Tool

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug(text: str) -> str:
    return _SLUG_RE.sub("-", text.lower()).strip("-")[:60] or "candidate"


def make_record_candidate() -> Tool:
    def handler(inp: dict) -> str:
        title = (inp.get("title") or "").strip()
        if not title:
            return "ERROR: title is required."
        target = (inp.get("target") or "unknown").strip()
        cwe = (inp.get("cwe") or "").strip()
        hypothesis = (inp.get("hypothesis") or "").strip()
        evidence = (inp.get("evidence") or "").strip()
        gates = inp.get("gates_passed") or []
        if isinstance(gates, str):
            gates = [gates]
        gate_set = {g.strip().lower() for g in gates}

        stamp = datetime.now().strftime("%Y-%m-%d")
        gate_line = lambda name, key: f"- [{'x' if key in gate_set else ' '}] {name}"
        checklist = "\n".join([
            gate_line("Gate 1 — Root cause identified (exact flaw, not symptom)", "root_cause"),
            gate_line("Gate 2 — Reproduced (minimal deterministic PoC/trigger)", "reproduced"),
            gate_line("Gate 3 — Impact proven (primitive/priv/RCE demonstrated)", "impact"),
            gate_line("Gate 4 — Scope-checked (in scope, security-relevant)", "scope"),
        ])
        verified = gate_set.issuperset({"root_cause", "reproduced", "impact", "scope"})

        body = f"""---
type: research-note
source: argus-agent
target: {target}
cwe: {cwe}
status: {"VERIFIED — promote to Outputs/" if verified else "candidate — leads only, NOT reported"}
created: {stamp}
---

# {title}

> Generated by ARGUS. A candidate is **not** a finding until all four gates pass.
> Nothing here is reported until Muhammed has personally reproduced it.

**Target:** {target}
**Class:** {cwe or "(unclassified)"}

## Falsifiable question
{hypothesis or "(state the hypothesis as a question that could be proven false)"}

## Evidence gathered
{evidence or "(paste tool output / disassembly / ACLs that support or refute this)"}

## Verification gates
{checklist}

## Next action
- (what single experiment would move the weakest unchecked gate?)

## Links
- [[Targets]]
"""
        process_dir = config.VR_DIR / "Process"
        process_dir.mkdir(parents=True, exist_ok=True)
        fname = f"argus-{stamp}-{_slug(target)}-{_slug(title)}.md"
        path = process_dir / fname
        n = 1
        while path.exists():
            path = process_dir / f"{fname[:-3]}-{n}.md"
            n += 1
        try:
            path.write_text(body, encoding="utf-8")
        except OSError as e:
            return f"ERROR writing note: {e}"
        status = "VERIFIED (all gates)" if verified else f"CANDIDATE ({len(gate_set)}/4 gates)"
        out = f"Recorded {status} -> {path}"

        # Severity verification — prevent overclaimed critical bugs from
        # reaching Muhammed without evidence. Runs on every recorded candidate.
        try:
            from .. import severity
            sev = severity.classify_severity(
                title=title, cwe=cwe, hypothesis=hypothesis,
                evidence=evidence, target=target,
            )
            out += "\n\n" + severity.format_severity_banner(sev)
        except Exception:
            pass  # severity module optional, never block a recording

        # Award XP / advance the hunter level-up system. Never let a progression
        # error interfere with the actual finding being recorded.
        try:
            from .. import progression
            res = progression.award_for_candidate({
                "title": title, "target": target, "cwe": cwe,
                "hypothesis": hypothesis, "gates_passed": sorted(gate_set),
                "verified": verified,
            })
            out += "\n" + progression.feedback_line(res)
        except Exception:
            pass
        return out

    return Tool(
        name="record_candidate",
        description=(
            "Write a candidate lead into the vault's Process/ folder with the "
            "4-gate verification checklist. Use this to log every hypothesis "
            "(including dead ends). Only mark gates_passed for gates you have "
            "ACTUALLY proven with evidence — never inflate. A candidate is not a "
            "reportable finding until all four gates pass and Muhammed reproduces it."
        ),
        input_schema={
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "target": {"type": "string"},
                "cwe": {"type": "string", "description": "e.g. 'CWE-427 DLL search-order hijack'."},
                "hypothesis": {"type": "string", "description": "The falsifiable question this lead tests."},
                "evidence": {"type": "string", "description": "Concrete tool output / disassembly / ACLs supporting or refuting it."},
                "gates_passed": {
                    "type": "array",
                    "items": {"type": "string", "enum": ["root_cause", "reproduced", "impact", "scope"]},
                    "description": "Which of the four gates are genuinely proven. Be conservative.",
                },
            },
            "required": ["title", "target", "hypothesis"],
        },
        handler=handler,
    )
