"""Sigma rule generation — behavioral detection-as-code from a detonation.

Completes the detection trio: YARA catches the file, IOCs list the indicators,
and Sigma catches the *behavior* in logs (Sysmon / Windows events), SIEM-agnostic.
Maps a run's behavioral findings to Sigma logsource categories:

  spawned child processes  -> process_creation   (attack.t1059)
  C2 IPs / domains         -> network_connection  (attack.t1071)
  persistence keys         -> registry_set        (attack.t1547.001)
  dropped executables      -> file_event          (attack.t1105)

Rules are `status: experimental` candidates — review before deploying. Pure
stdlib (hand-rendered YAML); the rule-building core is a pure, tested function.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path


def _rule_id(sha: str, category: str) -> str:
    """Deterministic UUIDv4-shaped id from (sha, category) — stable/reproducible."""
    h = hashlib.sha256(f"{sha}:{category}".encode()).hexdigest()
    return f"{h[0:8]}-{h[8:12]}-4{h[13:16]}-{h[16:20]}-{h[20:32]}"


def _basename(p: str) -> str:
    return p.replace("/", "\\").rsplit("\\", 1)[-1]


def rules_from(struct: dict) -> list[dict]:
    """Pure: behavioral findings -> a list of Sigma rule specs."""
    from .ioc import extract_from
    iocs = extract_from(struct, struct.get("static"))
    sample = struct.get("sample") or "sample"
    sha = struct.get("sha256", "")
    rules: list[dict] = []

    procs = [p for p in (struct.get("spawned") or []) if p]
    if procs:
        images = sorted({"\\" + _basename(p) for p in procs})
        rules.append({"category": "process_creation", "title": f"Suspicious child process — {sample}",
                      "tags": ["attack.t1059"], "level": "medium", "sha": sha,
                      "selection": {"Image|endswith": images}})

    if iocs["ips"] or iocs["domains"]:
        sel = {}
        if iocs["ips"]:
            sel["DestinationIp"] = iocs["ips"]
        if iocs["domains"]:
            sel["DestinationHostname"] = iocs["domains"]
        rules.append({"category": "network_connection", "title": f"C2 network connection — {sample}",
                      "tags": ["attack.t1071"], "level": "high", "sha": sha, "selection": sel})

    if struct.get("persistence"):
        rules.append({"category": "registry_set", "title": f"Registry persistence — {sample}",
                      "tags": ["attack.t1547.001"], "level": "high", "sha": sha,
                      "selection": {"TargetObject|contains": list(struct["persistence"])[:10]}})

    if iocs["files"]:
        names = sorted({"\\" + _basename(f) for f in iocs["files"]})
        rules.append({"category": "file_event", "title": f"Dropped executable — {sample}",
                      "tags": ["attack.t1105"], "level": "medium", "sha": sha,
                      "selection": {"TargetFilename|endswith": names}})

    return rules


def _yv(v) -> str:
    """YAML-safe single-quoted scalar (escapes internal quotes; keeps backslashes)."""
    return "'" + str(v).replace("'", "''") + "'"


def render(spec: dict) -> str:
    lines = [
        f"title: {spec['title']}",
        f"id: {_rule_id(spec.get('sha', ''), spec['category'])}",
        "status: experimental",
        "description: Auto-generated by ARGUS from dynamic analysis (candidate — review before deploying)",
        "references:",
        f"    - {spec.get('sha', '')}",
        "author: ARGUS",
        "tags:",
    ]
    lines += [f"    - {t}" for t in spec["tags"]]
    lines += ["logsource:", f"    category: {spec['category']}", "    product: windows",
              "detection:", "    selection:"]
    for field, vals in spec["selection"].items():
        if isinstance(vals, list):
            lines.append(f"        {field}:")
            lines += [f"            - {_yv(v)}" for v in vals]
        else:
            lines.append(f"        {field}: {_yv(vals)}")
    lines += ["    condition: selection", f"level: {spec['level']}"]
    return "\n".join(lines) + "\n"


def generate(struct: dict) -> dict:
    rules = rules_from(struct)
    text = "\n---\n".join(render(r) for r in rules) if rules else ""
    return {"count": len(rules), "text": text, "rules": rules}


def generate_run(run_dir: str) -> dict:
    fj = Path(run_dir) / "findings.json"
    if not fj.exists():
        return {"error": f"no findings.json in {run_dir}"}
    return generate(json.loads(fj.read_text(encoding="utf-8")))
